[package]
name = "arkworks_poseidon_benchmark"
version = "0.0.1"
authors = ["The Tachyon Authors <tachyon-discuss@kroma.network>"]
edition = "2021"
rust-version = "1.56.1"
description = """
Arkworks Poseidon Hash Benchmark
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/kroma-network/tachyon"
documentation = "https://docs.rs/arkworks_benchmark"
readme = "README.md"
categories = ["cryptography"]
keywords = ["tachyon", "benchmark", "arkworks"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "^0.4.0", default-features = false }
ark-bn254 = "0.4.0"
ark-crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives.git", features = [
    "sponge",
], tag = "v0.4.0" }
tachyon_rs = { path = "../../../tachyon/rs" }
